name: Django CI

on:
  push:
    branches: ["main", "backend"] # adapte les branches
  pull_request:
    branches: ["main", "backend"]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres: # si tu utilises PostgreSQL
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10" # adapte ta version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-django pytest-cov

      - name: Run migrations
        env:
          DJANGO_SETTINGS_MODULE: config.settings
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
        run: |
          python manage.py migrate

      - name: Run tests with pytest
        env:
          DJANGO_SETTINGS_MODULE: config.settings
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
        run: |
          pytest --cov=. --maxfail=1 --disable-warnings -v
